### PR TITLE
Fix missing localization

### LINKED ISSUE #72: Country names are not localized anymore
Hi,

I noticed that starting from this [commit](https://github.com/imtoori/CountryCodePicker/commit/1e9495cf249a82468f0f45552f341ab8eb884076) , the country names in the dialog as well as the picker itself is not being localized anymore.

It is displaying the original name from the country_codes in the example app included in the library. 

I debugged it and for some reason, the function `didUpdateWidget()` is never called, even when showing the dialog and selecting a country.

I'll do further testing asap and see what I can do.

### PR DESCRIPTION
**Pull request by themobilecoder**
I moved the part that localizes the elements from the`didUpdateWidget` to`build` method.

Fixes #72

### CODE REVIEW

**Comment by imtoori** [comment]
I can't understand why `didUpdateWidget` is not working anymore...
Also the build method is called every time something changes and that's extra work everytime

**Comment by themobilecoder** [comment]
Hi, @imtoori 

In that case, you are right that this change would do additional work every time the user selects a country.

Have you tried it in your machine whether the didUpdateWidget is being called? I realized that it might be due to my flutter version at **beta** channel.

I will try switching to stable and see.

**Comment by imtoori** [comment]
That makes sense, maybe this other issue is related to a beta version of the framework https://github.com/imtoori/CountryCodePicker/issues/68

**Comment by themobilecoder** [comment]
Unfortunately, the issue still persists.

I did change to stable channel, did fresh clone of the project, put some print logs and installed the example app on an iPhone simulator.

initState is being called, but not the didUpdateWidget, so the localization does not happen.

The only time didUpdateWidget was called was when I did a Hot Reload, but aside from that it was never called elsewhere. So doing a hot reload does the localization.

@imtoori could you verify if localisation works on your machine?

**Comment by imtoori** [comment]
I tried and you are right, it's not working.

I'm sorry to keep closing you prs, but I think this is a better solution #74 what do you think? 
Could you try it?

**Comment by themobilecoder** [comment]
Hi @imtoori,

I agree that #74 is better because it's called once after initState where the context has been initialized already. I also tested the change. Thanks!

**Pull request closed without merging**
