### PR TITLE
Allow to filter countries by locale in the dialog

### LINKED ISSUE #48: Uniform special characters for search
I had an issue searching for Mexico, as I have the US keyboard layout I don't have the é. I had to search with the tilde for it to show up. Is there anyway to ignore special characters on the search function?

### LINKED ISSUE #62: Country filter is not working properly
After adding `CountryLocalizations.delegate` it change the name.
But after that search not work as per new name.
Ex. Before translation "India" show as "भारत" 
so for select that i have to type in hindi. But after adding  `CountryLocalizations.delegate` It show as "India" but still i have to type "भारत" in hindi to select it.

IMG_20200330_151413
IMG_20200330_151441

### PR DESCRIPTION
**Pull request by themobilecoder**
This commit is for letting the user search / filter a country in the dialog using the selected locale.

Fixes #62 and 
Fixes #48 

I added a flag in the constructor so that a user can still search using the original name in the country_codes json file.

### CODE REVIEW

**Comment by AhsanAyaz** [comment]
Thanks for the PR @themobilecoder .
@imtoori can you please merge this and release a new version. This is quite crucial for many apps who're using internationalization 🙂 
Thanks.

**Comment by imtoori** [comment]
Thank you very much
I'll review it asap today

**Comment by themobilecoder** [comment]
There could be a better solution than this commit as this is just a quick fix. This implementation always localise the whole of country_codes every time the dialog is shown.

**Comment by imtoori** [comment]
I think `filterByLocale` is a bit "useless" in the sense that naturally the filter should be performed using locale. Don't you think?

**Comment by imtoori** [comment]
https://github.com/imtoori/CountryCodePicker/pull/70
I think this is better, what do you think @themobilecoder ?

**Comment by AhsanAyaz** [comment]
@imtoori your PR looks good.

**Comment by themobilecoder** [comment]
> https://github.com/imtoori/CountryCodePicker/pull/70
> I think this is better, what do you think @themobilecoder ?

I agree! Updating the search is better. Thanks @imtoori!

**Pull request closed without merging**
