### PR TITLE
Shows the flag only when closed

### PR DESCRIPTION
**Pull request by simon-twonary**
currently, the flag `showFlagMain` has no effect on the Text widget

### CODE REVIEW

**Comment by imtoori** [comment]
I don't think this is the right logic.
Also the current is not really nice.
`showFlag` is the default and using `showFlagMain` or `showFlagDialog` you can hide the flag in the main or the dialog widget, but you can't show it only in one place using those properties.
I think that's the real problem. I'm preparing a pr

**Comment by imtoori** [comment]
https://github.com/imtoori/CountryCodePicker/pull/78 @simon-twonary what do you think?

**Comment by simon-twonary** [comment]
Hi, the behavior I was expecting is to hide the Text(Country Code and Country Name). 

In your PR #78, I don't see a way to hide the text field when the dialog is not showing. 


Use case: In my design, the Country Code is part of the TextField.
 
IMG_4115


IMG_4116

**Comment by imtoori** [comment]
ok I got it
`showFlagMain` controls the flag, I'll add another prop to hide the text

**Pull request merged**
