### PR TITLE
override didUpdateWidget to react to initlialSelection change

### PR DESCRIPTION
**Pull request by matteobertino**
In my application I found this change necessary to change initialSelction on rebuild of the widget tree

### CODE REVIEW

**Comment by Xentraxx** [comment]
I've been waiting for this pull request! I couldn't set a State with the initialSelection either.

**Comment by imtoori** [comment]
Mhh I'm not understanding the problem guys. Could you elaborate? Thanks

**Comment by Xentraxx** [comment]
I have to admit that I am not an expert on flutter but lets take my code for example:

`class PhoneNrInput extends StatelessWidget {
  final phoneNrController = TextEditingController();
  final CountryCode countryCode = CountryCode();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    CountryCodePicker(
                      initialSelection: ui.window.locale.countryCode,
                      onInit: (countryCodeTemp) =>
                          countryCode.dialCode = countryCodeTemp.dialCode,
                      onChanged: (countryCodeTemp) =>
                          countryCode.dialCode = countryCodeTemp.dialCode,
                      textStyle:
                          TextStyle(fontSize: 25, fontWeight: FontWeight.bold),
                    ),
                    Flexible(
                      child: TextField(
                        autocorrect: false,
                        maxLines: 1,
                        style: TextStyle(
                            fontSize: 25, fontWeight: FontWeight.bold),
                        keyboardType: TextInputType.phone,
                        controller: phoneNrController,
                        onSubmitted: (text) {
                          authentificateWithPhoneNr(phoneNrController.text,
                              countryCode.dialCode, context);
                        },
                      ),
                    )
                  ],
                ),],
            )),
      ),
    );
  }

  @protected
  @mustCallSuper
  void dispose() {
    phoneNrController.dispose();
  }
}
`
If I change the Country (onChange gets called) everything works just fine. The TextEditingController gets the dial code and when I submit the TextField, the function recieves the dial code which has been stored in countryCode.dialCode. CountryCodePicker runs the onInit function and the countryCode is beeing set. Unfortunately it seems like some magic is happening then which reruns onInit again and sets my country Code variable to null again.

@matteobertino is probably able to get in more detail as I don't have a deep understanding of flutter and what exactly he is changing. But it seems like this could resolve my problem.

**Comment by matteobertino** [comment]
I don't know if it's right but this change worked for me:
I put a CountryCodePicker inside a StatefulWidget. Whenever the parent Widget was rebuilt, the CountryCodePicker is detached from the widget tree and rebuilds. Since CountryCodePicker is a StatefulWidget, it's State is preserved at every rebuild of the Widget. Since selectedItem was only initialized in initState(), it was initialised only at the first build of the Widget and the first creation of it's State. Since didUpdateWidget is called every time the State is attached to a Widget, I thought it was a good idea to use it to reinitialize selecteItem to match initialSelection if the Widget's initialSelection changed.

Without this change I could't change initialSelection after the first build.

**Comment by imtoori** [comment]
Ok, I'm trying to reproduce the problem, but I got it

However I think that according to documentation you should call 
`super.didUpdateWidget(oldWidget);`
on the first line of the override method

**Comment by matteobertino** [comment]
> However I think that according to documentation you should call
> `super.didUpdateWidget(oldWidget);`
> on the first line of the override method

Right. Done.
Thank you

**Pull request merged**
